create database grocery;
use grocery;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
--  1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior
-- 1.How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

-- 2.Which customers have placed the highest number of orders?
SELECT 
    c.cust_id,
    c.cust_name,
    COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o
ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC;

-- 3. What is the total and average purchase value per customer?
SELECT
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase,
    AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o
ON c.cust_id = o.cust_id
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name;

-- 4. Who are the top 5 customers by total purchase amount?
SELECT
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_spent
FROM customers c
JOIN orders o
ON c.cust_id = o.cust_id
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_spent DESC
LIMIT 5;

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- 1. How many products exist in each category?
SELECT 
    c.cat_id,
    c.cat_name,
    COUNT(p.prod_id) AS total_products
FROM categories c
LEFT JOIN products p
ON c.cat_id = p.cat_id
GROUP BY c.cat_id, c.cat_name;

-- 2. What is the average price of products by category?
SELECT
    c.cat_id,
    c.cat_name,
    AVG(p.price) AS avg_price
FROM categories c
JOIN products p
ON c.cat_id = p.cat_id
GROUP BY c.cat_id, c.cat_name;

-- 3. Which products have the highest total sales volume (by quantity)?
SELECT
    p.prod_id,
    p.prod_name,
    SUM(od.quantity) AS total_quantity_sold
FROM products p
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_quantity_sold DESC;


-- 4. What is the total revenue generated by each product?
SELECT
    p.prod_id,
    p.prod_name,
    SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue DESC;

-- 5. How do product sales vary by category and supplier?
SELECT
    c.cat_name,
    s.sup_name,
    p.prod_name,
    SUM(od.quantity) AS total_units_sold,
    SUM(od.total_price) AS total_revenue
FROM order_details od
JOIN products p
ON od.prod_id = p.prod_id
JOIN categories c
ON p.cat_id = c.cat_id
JOIN supplier s
ON p.sup_id = s.sup_id
GROUP BY
    c.cat_name,
    s.sup_name,
    p.prod_name
ORDER BY total_revenue DESC;

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- 1. How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;
-- 2. What is the average value per order?
SELECT
    AVG(order_total) AS avg_order_value
FROM (
    SELECT
        ord_id,
        SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) x;

-- 3. On which dates were the most orders placed?
SELECT
    order_date,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;

-- 4. What are the monthly trends in order volume and revenue?
SELECT
    DATE_FORMAT(o.order_date,'%Y-%m') AS month,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY DATE_FORMAT(o.order_date,'%Y-%m')
ORDER BY month;

-- 5. How do order patterns vary across weekdays and weekends?
SELECT
    CASE
        WHEN DAYOFWEEK(order_date) IN (1,7)
        THEN 'Weekend'
        ELSE 'Weekday'
    END AS order_type,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_type;


-- 4. Supplier Contribution 
-- Identify the most active and profitable suppliers.
-- 1. How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- 2. Which supplier provides the most products?
SELECT
    s.sup_id,
    s.sup_name,
    COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p
ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_products DESC;

-- 3. What is the average price of products from each supplier?
SELECT
    s.sup_id,
    s.sup_name,
    AVG(p.price) AS avg_product_price
FROM supplier s
JOIN products p
ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name;

-- 4. Which suppliers contribute the most to total product sales (by revenue)?
SELECT
    s.sup_id,
    s.sup_name,
    SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p
ON s.sup_id = p.sup_id
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- 1. How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS employees_processed_orders
FROM orders;


-- 2. Which employees have handled the most orders?
SELECT
    e.emp_id,
    e.emp_name,
    COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o
ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_orders DESC;

-- 3. What is the total sales value processed by each employee?
SELECT
    e.emp_id,
    e.emp_name,
    SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o
ON e.emp_id = o.emp_id
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales DESC;


-- 4. What is the average order value handled per employee?
SELECT
    e.emp_id,
    e.emp_name,
    AVG(order_total) AS avg_order_value
FROM employees e
JOIN (
    SELECT
        o.emp_id,
        o.ord_id,
        SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od
    ON o.ord_id = od.ord_id
    GROUP BY o.emp_id, o.ord_id
) x
ON e.emp_id = x.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;

-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- 1. What is the relationship between quantity ordered and total price?
SELECT
    quantity,
    AVG(total_price) AS avg_total_price,
    SUM(total_price) AS total_revenue,
    COUNT(*) AS number_of_orders
FROM order_details
GROUP BY quantity
ORDER BY quantity;

-- 2. What is the average quantity ordered per product?
SELECT
    p.prod_id,
    p.prod_name,
    AVG(od.quantity) AS avg_quantity_ordered
FROM products p
JOIN order_details od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_quantity_ordered DESC;

-- 3. How does the unit price vary across products and orders?
SELECT
    o.ord_id,
    p.prod_id,
    p.prod_name,
    od.each_price,
    od.quantity,
    od.total_price
FROM order_details od
JOIN orders o
ON od.ord_id = o.ord_id
JOIN products p
ON od.prod_id = p.prod_id
ORDER BY p.prod_name, o.ord_id;